# pool:
#   name: 'arun1projectDemo'

# steps:
# - script: echo "Hello from self-hosted agent"

trigger:
  branches:
    include:
      - main   # Runs on commits to main branch

pool:
  name: 'arun1projectDemo'

variables:
  resourceGroupName: 'arun1testing-RG'
  subscriptionId: 'fa236b7f-954f-4834-8294-f0a2b5cea417'
  factoryName: 'arun1adfTest'
  templatePath: 'arun1adf/ARMTemplateForFactory.json'
  parametersPath: 'arun1adf/ARMTemplateParametersForFactory.json'

stages:
- stage: DeployADF
  displayName: "Deploy Azure Data Factory ARM template"
  jobs:
  - job: Deploy
    displayName: "Deploy ADF to Test"
    steps:
    - checkout: self
      persistCredentials: true
      clean: true

    - script: dir
      displayName: 'List files (cmd.exe)'

    - task: AzureCLI@2
      displayName: "Deploy ARM template to Test ADF"
      inputs:
        azureSubscription: 'arun1devopsSrvConn'   # Service connection in DevOps
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group show --name $(resourceGroupName)
          az deployment group create `
            --subscription $(subscriptionId) `
            --resource-group $(resourceGroupName) `
            --template-file $(templatePath) `
            --parameters @$(parametersPath) `
            --parameters factoryName=$(factoryName) `
            --name adf_test_deployment_$(Build.BuildId)
