# pool:
#   name: 'arun1projectDemo'

# steps:
# - script: echo "Hello from self-hosted agent"

trigger:
  branches:
    include:
      - main   # Start pipeline when changes are merged to main

pool:
  name: 'arun1projectDemo'

variables:
  resourceGroupName: 'arun1testing-RG'
  subscriptionId: 'fa236b7f-954f-4834-8294-f0a2b5cea417'
  devFactoryName: 'arun1adf'       # Source ADF (dev)
  testFactoryName: 'arun1adfTest'  # Target ADF (test)

stages:

# =====================
# 1. Publish Stage
# =====================
- stage: PublishADF
  displayName: "Publish ADF artifacts to adf_publish"
  jobs:
  - job: Publish
    displayName: "Generate ARM templates and push to adf_publish"
    steps:
    - checkout: self
      persistCredentials: true
      clean: true

    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: "Install Node.js"

    - script: |
        npm install -g @microsoft/azure-data-factory-utilities

        echo "Generating ARM templates from $(devFactoryName)..."
        adf publish `
          --root ./arun1adf `
          --factory-name $(devFactoryName) `
          --subscription-id $(subscriptionId) `
          --resource-group $(resourceGroupName) `
          --output-folder ./adf_publish

        echo "Committing templates to adf_publish branch..."
        git config user.email "build@devops"
        git config user.name "Azure DevOps Build"
        git fetch origin
        git checkout adf_publish
        cp ./adf_publish/* .
        git add .
        git commit -m "Auto-publish from main ($(Build.BuildId))" || echo "No changes to commit"
        git push origin adf_publish
      displayName: "Run ADF publish and commit ARM templates"

# =====================
# 2. Deploy Stage
# =====================
- stage: DeployADF
  displayName: "Deploy ADF ARM templates to Test"
  dependsOn: PublishADF
  jobs:
  - job: Deploy
    displayName: "Deploy ADF to Test Factory"
    steps:
    - checkout: self
      persistCredentials: true
      clean: true

    - script: git checkout adf_publish
      displayName: "Switch to adf_publish branch"

    - task: AzureCLI@2
      displayName: "Deploy ARM template to Test ADF"
      inputs:
        azureSubscription: 'arun1devopsSrvConn'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Deploying ARM templates to $(testFactoryName)..."
          az deployment group create `
            --subscription $(subscriptionId) `
            --resource-group $(resourceGroupName) `
            --template-file ARMTemplateForFactory.json `
            --parameters @ARMTemplateParametersForFactory.json `
            --parameters factoryName=$(testFactoryName) `
            --name adf_test_deployment_$(Build.BuildId)


# trigger:
#   branches:
#     include:
#       - main   # Runs on commits to main branch

# pool:
#   name: 'arun1projectDemo'

# variables:
#   resourceGroupName: 'arun1testing-RG'
#   subscriptionId: 'fa236b7f-954f-4834-8294-f0a2b5cea417'
#   factoryName: 'arun1adfTest'
#   templatePath: 'arun1adf/ARMTemplateForFactory.json'
#   parametersPath: 'arun1adf/ARMTemplateParametersForFactory.json'

# stages:
# - stage: DeployADF
#   displayName: "Deploy Azure Data Factory ARM template"
#   jobs:
#   - job: Deploy
#     displayName: "Deploy ADF to Test"
#     steps:
#     - checkout: self
#       persistCredentials: true
#       clean: true

#     - script: dir
#       displayName: 'List files (cmd.exe)'

#     - task: AzureCLI@2
#       displayName: "Deploy ARM template to Test ADF"
#       inputs:
#         azureSubscription: 'arun1devopsSrvConn'   # Service connection in DevOps
#         scriptType: 'ps'
#         scriptLocation: 'inlineScript'
#         inlineScript: |
#           az group show --name $(resourceGroupName)
#           az deployment group create `
#             --subscription $(subscriptionId) `
#             --resource-group $(resourceGroupName) `
#             --template-file $(templatePath) `
#             --parameters @$(parametersPath) `
#             --parameters factoryName=$(factoryName) `
#             --name adf_test_deployment_$(Build.BuildId)
